name: Desktop macOS
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build DMG
        run: ./gradlew :desktop:createDistributable

      - name: Codesign + Notarize
        env:
          IDENTITY: ${{ secrets.MACOS_IDENTITY }}
          AC_PROFILE: ${{ secrets.MACOS_AC_PROFILE }}
        run: |
          bash scripts/macos_sign_notarize.sh "${GITHUB_REF_NAME#v}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG
          path: desktop/build/compose/binaries/main/dmg/*.dmg
