name: Desktop CI

on:
  push:
    branches: [ main, refactor/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Desktop
        run: ./gradlew :desktopApp:assemble --stacktrace --no-daemon

  package:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Create distributable (best-effort)
        run: ./gradlew :desktopApp:createDistributable --stacktrace --no-daemon
        continue-on-error: true

      - name: Upload distributable
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-distributable
          path: desktopApp/build/compose/binaries/main/**

