name: Desktop Windows
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v3

      - name: Decrypt PFX
        run: |
          echo "${{ secrets.WIN_PFX_BASE64 }}" > pfx.b64
          certutil -decode pfx.b64 aifactory.pfx

      - name: Build + Sign
        env:
          PFX_PATH: ${{ github.workspace }}\aifactory.pfx
          PFX_PASS: ${{ secrets.WIN_PFX_PASS }}
        run: |
          pwsh scripts/win_sign.ps1 "${env:GITHUB_REF_NAME -replace '^v',''}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installers
          path: |
            desktop/build/compose/binaries/main/exe/*.exe
            desktop/build/compose/binaries/main/msi/*.msi
